spring:
  h2:
   console:
     enabled: true
     path: '/console'
  datasource:
     url: 'jdbc:h2:file:C:/Users/janek/OneDrive/VETO- project/TIN_Veto_project/veto-db'
  jpa:
    hibernate:
      ddl-auto: validate
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'Veto'
  resource: 'veto-client'
  public-client: true