spring:
  h2:
   console:
     enabled: true
     path: '/console'
  datasource:
     url: 'jdbc:h2:file:C:/Users/janek/OneDrive/TIN - project/project/veto-db'
  jpa:
    hibernate:
      ddl-auto: validate